
@dominio = http://localhost:3080
@token = eyJhbGciOiJSUzI1NiIsImVuYyI6IkEyNTZHQ00ifQ.eyJlbWFpbCI6Ikp1YW5pdG8yQGR1ZGkuY2wiLCJpc3MiOiJwcmluY2lwYWwiLCJpYXQiOjE2NTgyNDg2Mzd9.P6aNaIPni7wkweVbWAVTd1_ERFigCqXp9-lDejuKbukd6CJr0Gpq7vXVxsTVYtsNASJxb7XQAsFCfXew9D5Gp97KUJlLCYCgEvE8irppdQuZAvGnSn1xsNJxXK91Kh6JslCeRdYUp-buTreZ8Ec8eZaQ8kM7Ep6reFVf_a-zjabE3fL2B3AqXGwP8lOG-rcXUmrOOPhpFnqT4YTFcwbYsxcyTcNzUjOtW00qGPgMlEfxx4BGX2qOVgzrfp_77myVtaGby5dkh9x-81_K1oEVqv8x3k7cD3p2YeQfE7NzEmwJ1iu1HwmPULxNNWK2Vzou7ruj93-_x2A9rI6116TDZg


### login con email y pass
POST {{dominio}}/login
Content-Type: application/json

{
	"email": "Juanito2@dudi.cl",
	"pass": "123456"
}



### Crea un nuevo usuario
POST {{dominio}}/usuario
Content-Type: application/json

{
	"nombre": "<h1>Jua();nito</h1>",
	"email": "Juanito2@dudi.cl",
	"pass": "123456"
}
 

### Cofirma usuario con codigo enviado al correo
POST {{dominio}}/usuario/confirmacionCorreo/conCodigo
Content-Type: application/json
Authorization: Bearer {{token}} 

{
	"codigo": "7711",
	"email": "Juanito2@dudi.cl"
}

@usuarioID = 980798797
### Asigna una web a un usuario
POST {{dominio}}/usuario/980798797/web
Content-Type: application/json
Authorization: Bearer {{token}} 

{
	"web": "gob",
	"tipoAcceso": "administrador"
}





### Guarda credenciales para correo en bbdd
POST {{dominio}}/correos/credenciales
Content-Type: application/json

{
	"SMTPUsername": "string",
	"SMTPPassword": "string",
	"dominio": "xxxx.cl"
}
